require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.harpoon")
require("core.plugin_config.vim-fugitive")
require("core.plugin_config.catppuccin")
require("core.plugin_config.nvim-lspconfig")
require("core.plugin_config.cmp")
